// <auto-generated />
using System;
using AR_Inventory.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AR_Inventory.Migrations
{
    [DbContext(typeof(Db))]
    partial class EntityContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("AR_Inventory.Entities.Models.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<float>("LocationX")
                        .HasColumnType("REAL");

                    b.Property<float>("LocationY")
                        .HasColumnType("REAL");

                    b.Property<float>("LocationZ")
                        .HasColumnType("REAL");

                    b.Property<float>("OrientationW")
                        .HasColumnType("REAL");

                    b.Property<float>("OrientationX")
                        .HasColumnType("REAL");

                    b.Property<float>("OrientationY")
                        .HasColumnType("REAL");

                    b.Property<float>("OrientationZ")
                        .HasColumnType("REAL");

                    b.Property<Guid?>("SpatialAnchorUuid")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
